import { PERMISSIONS } from "./Permission";

export const ROLE_PERMISSIONS = {
  tenantAdmin: [
    // Tenant
    PERMISSIONS.TENANT_VIEW,
    PERMISSIONS.TENANT_UPDATE,

    // Members
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_REMOVE,
    PERMISSIONS.MEMBER_ROLE_CHANGE,
    PERMISSIONS.MEMBER_VIEW,

    // Branch
    PERMISSIONS.BRANCH_CREATE,
    PERMISSIONS.BRANCH_UPDATE,
    PERMISSIONS.BRANCH_VIEW,

    // Product
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.INVENTORY_AUDIT_VIEW,

    // Inventory
    PERMISSIONS.INVENTORY_ADD,
    PERMISSIONS.INVENTORY_REMOVE,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_VIEW,

    // Analytics
    PERMISSIONS.ANALYTICS_VIEW,
  ],

  manager: [
    // Tenant
    PERMISSIONS.TENANT_VIEW,

    // Members
    PERMISSIONS.MEMBER_VIEW,

    // Branch
    PERMISSIONS.BRANCH_VIEW,

    // Product
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_VIEW,

    // Inventory
    PERMISSIONS.INVENTORY_ADD,
    PERMISSIONS.INVENTORY_REMOVE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_AUDIT_VIEW,

    // Analytics
    PERMISSIONS.ANALYTICS_VIEW,
  ],

  user: [
    // Tenant
    PERMISSIONS.TENANT_VIEW,

    // Branch
    PERMISSIONS.BRANCH_VIEW,

    // Product
    PERMISSIONS.PRODUCT_VIEW,

    // Inventory
    PERMISSIONS.INVENTORY_VIEW,
  ],
};
